_G.Utils = require("config.utils")

require("config.neovide")
require("config.options")
require("config.dependencies")
require("config.keymaps")
require("config.snacks")
require("config.treesitter")
require("config.folding")
require("config.git")
require("config.lsp")
require("config.diagnostics")
require("config.statuscolumn")
require("config.formatting")
require("config.completion")
require("config.copilot")
require("config.mini")
