_G.Utils = require("config.utils")

require("config.neovide")
require("config.options")
require("config.dependencies")
require("config.keymaps")
require("config.snacks")
require("config.treesitter")
require("config.folding")
require("config.git")
require("config.statuscolumn")
