return {
	file = " ",
	folder = "󰝰 ",
	signs = {
		fillchar = " ",
		diagnostics = {
			error = " ",
			warn = " ",
			info = " ",
			hint = " ",
		},
		git = {
			added = " ",
			changed = "󰜥 ",
			deleted = " ",
		},
		comments = {
			fix = " ",
			todo = " ",
			hack = " ",
			warn = " ",
			perf = " ",
			note = " ",
			test = " ",
		},
	},
	virtual_text = {
		color = " ",
		diagnostics = {
			error = "",
			warn = "",
			info = "",
			hint = "",
		},
	},
	statusline = {
		branch = " ",
		command = " ",
		recording = " REC",
		search_forward = "  ",
		search_backward = "  ",
		ruler = "󰦪 ",
	},
	lsp = {
		kinds = {
			text = "󰉿 ",
			method = "󰊕 ",
			func = "󰊕 ",
			constructor = "󰒓 ",
			field = "󰜢 ",
			variable = "",
			property = "󰖷 ",
			class = "󱡠 ",
			interface = "󱡠 ",
			struct = "󱡠 ",
			module = "󰅩 ",
			unit = "󰪚 ",
			value = "󰎠 ",
			enum = " ",
			enum_member = " ",
			keyword = "󰌋 ",
			constant = "󰏿 ",
			snippet = "󱄽 ",
			color = "󰏘 ",
			tailwind_color = " ",
			file = " ",
			reference = "󰬲 ",
			folder = "󰝰",
			event = "󱐋 ",
			operator = "󰆕 ",
			type_parameter = "󰬛 ",
		},
	},
}
